### ISSUE TITLE
geometry argument does not work for windowposition

### ISSUE THREAD

**Issue by othmar52** [oligau/xwax-1.5-osc#5]
starting xwax with an argument like "-g 1920x400+0+0" results in an vertically centered window instead of having the window on top of the screen. pretty sure the call of 'putenv("SDL_VIDEO_WINDOW_POS=%d,%d")' is not at the right place.

a hardcoded 'putenv("SDL_VIDEO_WINDOW_POS=0,0")' in interface.c:1839 (after calling load_fonts() ) works for me.

further the geometry argument does not support negative position-values like "1024x768+0-100"

**Comment by oligau** [comment]
Hi othmar52,

I believe this feature is actually implemented in upstream xwax. You might want to copy your message on xwax mailing list at xwax.org.

Thanks! !

**Comment by othmar52** [comment]
Oopz - you are right. sorry for blaming your wonderful osc-fork
I noticed that i have reported this issue back in 2012:
http://sourceforge.net/p/xwax/mailman/message/29043240/#msg29162207

**Comment by oligau** [comment]
I actually want this closed upstream too as I'll be playing with weird 
geometries and no windows manager embedded setup in the next months with 
xwax 1.6.
Thanks, are you testing xwax-osc branch? please tell us your finding on 
the mailing list... THANKS!

Olivier
